services:
  ai-pipeline:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - LOG_LEVEL=INFO
      - SITE_ID=dev-local
      - ENABLE_MODEL_LOADING=false
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./temp:/app/temp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 8G
    restart: unless-stopped
